### ISSUE TITLE
little help to use this

### ISSUE THREAD

**Issue by adrienvia** [vincent290587/ZwiftConverter#1]
hi, I find your converter when i was searching for some zwo files for zwift, and your little project is perfect for what i want to do, more quickly that make the zwo.
but my experience from visual studio is very poor, and I don't know what to do exactly, do i need to build it from the cmakelists first? and i don't know how and where to put the argument for this to be working... sorry for my noob question, i'm searching on the internet, bu maybe it's not that complicated, and i miss something... maybe a little step by step if it's not too long to explain. thanks in advance.

**Comment by adrienvia** [comment]
oups, okay, I think i figured it out, I just had to built it so, after it is done, i have the Zwifter.exe program, and i need to excecute the command from cmd... does it create automatique file? or i need to add > mynewfile.zwo

**Comment by vincent290587** [comment]
You will have to save the output in a file, and remove everything before the <workout_file> !

E.g.: Zwifter.exe input.txt > output_to_cleanup.zwo

**Comment by adrienvia** [comment]
yes, okay, wasn't sure about that, when i see the text before <workout_file> but okay, perfect =) thanks
