### ISSUE TITLE
does not seem to work with rpm in workout

### ISSUE THREAD

**Issue by adrienvia** [vincent290587/ZwiftConverter#2]
Hi, after tested you program, and maybe i'm doing something wrong, but it doesn't seem to work when there is a rpm target in the workout ( " 15min @ 65rpm, from 65 to 92% FTP ") for exemple
in the zwo file, it the add of Cadence="65" for exemple.

**Comment by vincent290587** [comment]
I used it yesterday with cadence and it worked, can you send your input file to me ? vincent.golle@gmail.com

**Comment by adrienvia** [comment]
oh, yes weird, it was a specific ramp with cadence, because i tried with a simple cadence, and it worked.
but not with this one:

7min from 44 to 75% FTP
30sec @ 109% FTP
3min @ 50% FTP
30sec @ 109% FTP
5min @ 50% FTP
15min @ 65rpm, from 65 to 92% FTP
5min @ 40% FTP
15min @ 65rpm, from 65 to 92% FTP
10min @ 50% FTP

**Comment by vincent290587** [comment]
I think that for now ramps cannot have cadence targets... Could be sent to the todo list !

**Comment by adrienvia** [comment]
yes, i tried to do it via zwofactory, and it worked, with the cadence="xx" at the end,

and i noted another to do list, it does not work with free ride either "1min free ride @ 65rpm" for example, and i had another one, with 5min 50sec, and it does not worked either, the 50sec seems to be the problem ;)

**Comment by vincent290587** [comment]
SHould be fixed now !

**Comment by adrienvia** [comment]
oups, i have a new issues now everytime :P it doesn't work anymore
"Assertion failed: res == 1, file ...\src\Zwifter.hpp, line 249"
i tried with a lot of input, I don't really know what's causing that...

**Comment by vincent290587** [comment]
I checked and found lots of bugs... Sorry about that !
It should now all be fixed !

**Comment by adrienvia** [comment]
thanks, this is really nice !! =) it works perfectly, and save me a lot of time !
