### ISSUE TITLE
Errors during run

### ISSUE THREAD

**Issue by victorypoint** [vincent290587/ZwiftConverter#3]
Zwifter.exe - System Error

The code execution cannot proceed because libgcc_s_seh-1.dll was not found. Reinstalling the program may fix this problem. 

The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem.

**Comment by vincent290587** [comment]
You'll need to compile the program yourself using the provided CMakeFile to avoid these errors
